### ISSUE TITLE
--key=VAL parsing broken in example

### ISSUE THREAD

**Issue by mboersma** [docopt/docopt.go#21]
This should succeed at parsing and print its args, but fails instead:

``` console
$ go run examples/options/options_example.go --ignore=E,W6
Usage:
  options_example [-hvqrf NAME] [--exclude=PATTERNS]
                     [--select=ERRORS | --ignore=ERRORS] [--show-source]
                     [--statistics] [--count] [--benchmark] PATH...
  options_example (--doctest | --testsuite=DIR)
  options_example --version
exit status 1
```

It appears argument parsing of the format --key=VAL is broken generally in docopt-go.

**Comment by the-shank** [comment]
@mboersma I dont think this is a bug. Basically the `PATH...` positional argument is not found in the example command that you have quoted. I think that is what is making it exit with status 1. I tried this by providing a positional argument to represent `PATH` and it worked fine.

I think we can close this as `invalid`
