### ISSUE TITLE
Versioning of library

### ISSUE THREAD

**Issue by jakubjedelsky** [docopt/docopt.go#27]
I want to prepare a package for Fedora and have a question - how versions will go? Do you want to follow python development and use the same versions or just to code without regular releases? Both answers are right (it's for nice implementation only) :) I can see 0.6.1 tag which is one year old and I'm not sure how it will continue.

**Comment by mboersma** [comment]
I think it's most convenient to follow the python releases if possible, but we may have to bump the patch release number ahead of the python version at some point.
