### ISSUE TITLE
Not returning ints

### ISSUE THREAD

**Issue by calmh** [docopt/docopt.go#3]
The documentation says "interface{} can be bool, int, string, []string.", implying (I guess?) that numeric arguments ought to be be an int in the arguments map. However, for options such as

```
  --scan-intv <s>  Repository scan interval, in seconds [default: 60]
```

the "60" is returned as a string-typed interface{}.

**Comment by zeroXten** [comment]
Huh. I too assumed that [default: 60] would return an int. atoi it is then I guess.

**Comment by aviddiviner** [comment]
Take a look at my fork, which handles this: https://github.com/aviddiviner/docopt-go#api

You can just access the values like so:
```go
secs, _ := opts.Int("--scan-intv")
```

There's some other helpful features, like binding to a struct, which does all type conversion for free.
