### ISSUE TITLE
Git subcommands example uses Go binary

### ISSUE THREAD

**Issue by alapidas** [docopt/docopt.go#32]
Is there a way to properly implement subcommands without using the Go binary to actually run them?  The use case is building + shipping + deploying a binary to boxes that do not have Go installed on them.

**Comment by the-shank** [comment]
@alapidas Instead of invoking subcommand logic using `goRun` as in the example, you could make separate usage strings (one for each command) and then `docopt.Parse()` them on the basis of the command. Basically something as shown below

```
mainUsage := `git <command> ....`

cloneUsage := 'git clone .....`
addUsage := 'git add .....`

func main(){
    args, _ := Parse(mainUsage, nil, true, "git version 1.7.4.4", true)

    cmd := args["<command>"].(string)

    switch cmd {
    case "clone":
        cloneArgs, _ := Parse(cloneUsage, nil, true, "", true)
        // handle clone command based on the above args
    case "add":
        addArgs, _ := Parse(addUsage, nil, true, "", true)
        // handle add command
}
```
I hope you get what I am suggesting.
