### ISSUE TITLE
Doesnt work with golang's way of defining arguments

### ISSUE THREAD

**Issue by satyamsi** [docopt/docopt.go#35]
If one uses docopt and at the same time uses a golang library like glog, due to the way these two parse, it difficult to even bring up a simple program.

**Comment by aviddiviner** [comment]
Can you elaborate on what your particular use case is? Are both packages supposed to be parsing `os.Args`?

**Comment by satyamsi** [comment]
golang has standard flag.Parse() and the way its used is that pretty much any package in go can add more command line options. Look at glog (https://github.com/golang/glog <https://github.com/golang/glog>) which uses some args such as -logtostderr=false (https://github.com/golang/glog/blob/master/glog.go <https://github.com/golang/glog/blob/master/glog.go>). 

Now if I use this package in my main function which uses docopt, the two don’t interact well together. 

Fundamentally, docopt and golang flags don’t work together and one has to jump through hoops to make it work.

Satyam

**Comment by fenollp** [comment]
I have given some thought to this and I think the best way for docopt.go to support `flag.Parse()` would be:
```golang
// my_main.go
package main
//go:generate docoptflag -u main.usage -n docoptstruct -o flagopt.go
// ^ generates a `var docoptstruct struct {...}` and 2 functions
...
func usage() string() { return `Usage: ....` }
func main() {
    docoptstructInit()
    ...
    flag.Parse()
    ...
    if *docoptstruct.MyBooleanFlag { ... }
    ...
}
```
which has the nice benefit of parsing `usage` at compile time!
I really want this to exist and will eventually look into it, but not soon.

@satyamsi would this kind of API suit you? I don't have much experience using `flag`.
Do you think that `docoptstructInit()` step (essentially calls to `flag.<Type>`) could be inserted directly into `init()`? I'm thinking it's nice to have the choice.

**Comment by ghostsquad** [comment]
This PR has recently been merged, and it makes significant improvements to getting typed values from the parsed args. https://github.com/docopt/docopt.go/pull/41

**Comment by ghostsquad** [comment]
Unfortunately, glog combines logging with command line parsing, which means it's not a great logger, as it has too many dependencies and makes too many assumptions. It's small enough that you could rip out the parsing stuff I'm sure. 

Docopt has 1 use case, command line parsing. It doesn't make sense to make different command line parsers compatible. Pick one and stick with it.
