### ISSUE TITLE
map[string]interface{} is cumbersome in Go

### ISSUE THREAD

**Issue by lukescott** [docopt/docopt.go#4]
I know that in Python a dict works well. But in Go a `map[string]interface{}` is actually cumbersome as you have to cast the value to string or int. `map[string]string` would be better as it eliminates the casting, but still creates a lot of unnecessary Unmarshal work.

I would suggest that docopt.go work more like Go's encoding packages (which uses `reflect`). Essentially something like this:

``` go
type Options struct {
    Command string `docopt:"<command>"`
    Speed int `docopt:"--speed"`
    Duration time.Duration `docopt:"--duration"` // Use time.ParseDuration
    Custom CustomValue `docopt:"--custom"` // Uses type UnmarshalDocopt interface
    Map map[string]string `docopt:""` // Put the rest of the options here
    Other string // Ignore this because it doesn't have docopt: tag
}

var doc = `...` // Ussage/Options text here

func main() {
    p := docopt.NewParser(doc, true, "App 2.0", false)
    var opt Options // can also be a map[string]string
    if err := p.Parse(&opt); err != nil {
        log.Fatal(err)
    }
}
```

This [package](https://github.com/jessevdk/go-flags) does something similar to the above example, but all the options are specified in tags, which get really ...really... long. With this you simply specify the name in a tag as you would in the map.

I would also consider it bad practice in Go to do an os.Exit inside of Parse/NewParser. The package user should have complete control over logging and exiting behavior inside their main. So I would suggest the above example look like this:

``` go
func main() {
    p := docopt.NewParser(doc, false) // Removed two middle options
    var opt Options
    if err := p.Parse(&opt); err != nil {
        log.Fatal(err)
    }
    if opt.Version { // Added Version bool `docopt:"--version"` to Options
        println("App 2.0")
        return
    }
    if opt.Help { // Added Help bool `docopt:"--help"` to Options
        println(doc) // OR p.PrintHelp()
        return
    }
}
```

Another neat idea (and perhaps this should be in another issue) would be to have the ability to fill values from an ini file like this:

``` go
type Options struct {
    Config string `docopt:"--config,ini"` // The "ini" flag tells docopt to read this string as a filename
    // ...
}
```

**Comment by sickill** [comment]
I concur, `map[string]interface{}` is really cumbersome to work with.

**Comment by tj** [comment]
As a default case (without tags) it would be cool to have your regular docopt setup, pass a struct, and camel-case the flags applying them to those values, or using the specified tag name.

That wouldn't work well with the args though, probably some other edge-cases as well

**Comment by SeeSpotRun** [comment]
A slight variation on what @lukescott suggested: https://github.com/SeeSpotRun/docopt.go/tree/cast looks to take the hard work out by passing the map[string]interface{} to a new func docopt.Cast().  It's a two-step process but it does offer the advantage of being able to populate several different options structures via additional calls to Cast().

**Comment by SeeSpotRun** [comment]
An update on the preceding:
* Moved this to a separate package (https://github.com/SeeSpotRun/coerce)
* Got it to also work with unexported (lowercase) fields (https://github.com/SeeSpotRun/coerce/blob/master/coerce.go#L83)
* Added flexibility re the map key punctuation (eg `--` and `-` prefixes and `<>` bracketing)

So general usage would be:
```
args, _ := docopt.Parse(os.Args[1:])

type options struct {
    command string
    speed   int
}
var opts options
err := coerce.Coerce(&opts, args, "--%s", "-%s", "<%s>")
```

**Comment by aviddiviner** [comment]
For those still interested, I've also got a fork which handles this somewhat more cleanly.
https://github.com/aviddiviner/docopt-go#api

Parser return a map of option names to the values parsed from argv, and an error or nil. You can get the values using the helpers, or just treat it as a regular map:

```go
flag, _ := opts.Bool("--flag")
secs, _ := opts.Int("<seconds>")
```

Additionally, you can `Bind` these to a struct, assigning option values to the
exported fields of that struct, all at once.

```go
var config struct {
  Command string `docopt:"<cmd>"`
  Tries   int    `docopt:"-n"`
  Force   bool   // Gets the value of --force
}
opts.Bind(&config)
```

**Comment by jkryanchou** [comment]
Awesome issue 👍 , I'm looking forward this feature for a long time.
