### ISSUE TITLE
question: would you be interested in a code review of the Go implementation?

### ISSUE THREAD

**Issue by campoy** [docopt/docopt.go#45]
Hi there,

I like the concept of documenting CLI tools the same way we do for REST APIs, but I am also a Go expert with opinions on the subject and feel like the API for the library is far from idiomatic.

I could send a bunch of PRs / issues or I could also do a video review (plus a big PR at the end) as I've previously done for my YouTube series [justforfunc](http://justforfunc.com).

Would you be interested on any of those? Is the API fixed or do you still accept non backwards compatible improvements?

Cheers,
Francesc

**Comment by luistm** [comment]
I would be very interested! :)

**Comment by campoy** [comment]
Awesome, I added it to my planning docs. I'll let you know when I review it
