### ISSUE TITLE
Whitespace is killing me

### ISSUE THREAD

**Issue by morganhein** [docopt/docopt.go#67]
For anyone interested in using docopt in Go, this seems like a great option. However, in it's current state, this package is harder to work with than the speed gains potentially provided by DocOpt. I am a **firm** believer in docopt and what it tries to do, so understand I really **want** this package to work, sadly it does not. 

**This issue is meant to steer people away until major issues are fixed.** 

The critical issues can be found by perusing the issues here in this repo, so I won't rehash them, but suffice to say i've wasted more hours debugging the parsing this package uses, then actually using it.

**Comment by celicoo** [comment]
Hey @morganhein 

I've recently launched my own version of docopt for go - [docli](https://github.com/celicoo/docli). The motivation was the lack of proper maintenance and new features in this one. It's production ready, although there are some limitations that will be properly addressed after I finish to write more effective tests.

I hope you like it.

P.S: If this type of comment is not allowed, please let me know.
